// Creates apps/demo-react192, demo-react191, demo-react18, demo-react182 and demo-react17: copies of
// the demo pinned to older React versions, so the same Playwright suite runs against each. npm nests
// the conflicting react/react-dom under the variant's own node_modules. 19.2 is there cause it is
// about half of react-dom's downloads, more than the 19.3 the demo itself runs.
//
//   node scripts/react-matrix.mjs        # (re)create the variants
//   npm install                          # picks up the new workspaces
//   npm run test -w apps/demo-react18    # or -w apps/demo-react17
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'apps/demo');
const demo = JSON.parse(fs.readFileSync(path.join(src, 'package.json'), 'utf8'));
// Ports of their own, clear of the demo's (5177, 5178) and of the Next.js suites' (5197, 5198, 5199).
const variants = [
  { name: 'demo-react192', react: '19.2.8', port: 5189, legacy: false, label: 'react192' },
  { name: 'demo-react191', react: '19.1.9', port: 5191, legacy: false, label: 'react191' },
  { name: 'demo-react18', react: '18.3.1', port: 5187, legacy: false, label: 'react18' },
  { name: 'demo-react182', react: '18.2.0', port: 5193, legacy: false, label: 'react182' },
  { name: 'demo-react17', react: '17.0.2', port: 5195, legacy: true, label: 'react17' },
];
const copy = ['src', 'e2e', 'index.html', 'devtools-hook.html', 'tsconfig.json', 'vite.config.ts', 'playwright.config.ts'];
// The tools the variants run are the demo's own, at the version it pins.
const devDependency = (name) => ({ [name]: demo.devDependencies[name] });

for (const v of variants) {
  const dir = path.join(root, 'apps', v.name);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  for (const f of copy) fs.cpSync(path.join(src, f), path.join(dir, f), { recursive: true });
  const env = `INP_PORT=${v.port} INP_LABEL=${v.label}${v.legacy ? ' INP_REACT_LEGACY=1' : ''}`;
  const pkg = {
    name: v.name,
    private: true,
    version: '0.0.1',
    type: 'module',
    description: `Demo pinned to React ${v.react}; generated by scripts/react-matrix.mjs, do not edit`,
    scripts: {
      dev: `${env} vite --port ${v.port} --strictPort`,
      // attribution covers what each React version reports; input-delay covers the join on Event.timeStamp,
      // which is the one that has to hold on a legacy root. The rest of the demo's specs are about the
      // browser and the bundler rather than the React version, and run on 19 only.
      test: `${env} playwright test attribution input-delay`,
      'test:prod': `${env} INP_MODE=prod INP_PORT=${v.port + 1} playwright test attribution input-delay`,
    },
    dependencies: { react: v.react, 'react-dom': v.react, 'react-inp-blame': '*' },
    devDependencies: { ...devDependency('@playwright/test'), ...devDependency('vite') },
  };
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');
  console.log(`${v.name}: React ${v.react}, port ${v.port}${v.legacy ? ', legacy root' : ''}`);
}
