// Creates apps/demo-react18 and apps/demo-react17: copies of the demo pinned to older
// React versions, so the same Playwright suite runs against each. npm nests the
// conflicting react/react-dom under the variant's own node_modules.
//
//   node scripts/react-matrix.mjs        # (re)create the variants
//   npm install                          # picks up the new workspaces
//   npm run test -w apps/demo-react18    # or -w apps/demo-react17
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'apps/demo');
const variants = [
  { name: 'demo-react18', react: '18.3.1', port: 5187, legacy: false, label: 'react18' },
  { name: 'demo-react17', react: '17.0.2', port: 5197, legacy: true, label: 'react17' },
];
const copy = ['src', 'e2e', 'index.html', 'tsconfig.json', 'vite.config.ts', 'playwright.config.ts', 'vite-plugin-display-names.ts'];

for (const v of variants) {
  const dir = path.join(root, 'apps', v.name);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  for (const f of copy) fs.cpSync(path.join(src, f), path.join(dir, f), { recursive: true });
  const env = `INP_PORT=${v.port} INP_LABEL=${v.label}${v.legacy ? ' INP_REACT_LEGACY=1' : ''}`;
  const pkg = {
    name: v.name,
    private: true,
    version: '0.0.1',
    type: 'module',
    description: `Demo pinned to React ${v.react}; generated by scripts/react-matrix.mjs, do not edit`,
    scripts: {
      dev: `${env} vite --port ${v.port} --strictPort`,
      test: `${env} playwright test attribution`,
      'test:prod': `${env} INP_MODE=prod INP_PORT=${v.port + 1} playwright test attribution`,
    },
    dependencies: { react: v.react, 'react-dom': v.react, 'inpector': '*' },
    devDependencies: { '@playwright/test': '1.59.1', vite: '^8.3.0' },
  };
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');
  console.log(`${v.name}: React ${v.react}, port ${v.port}${v.legacy ? ', legacy root' : ''}`);
}
